language: java

jdk:
  - oraclejdk8

addons:
  postgresql: "9.3"

before_script:
  # Create test databases
  - mysql -e "create database test;"
  - psql -c "create database test;" -U postgres

after_success:
  # Run test coverage and submit to Coveralls
  - gradle jacocoTestReport coveralls
