language: java

jdk:
  - oraclejdk8

before_script:
  # Create a test database
  - mysql -e "create database test;"

after_success:
  # Run test coverage and submit to Coveralls
  - gradle jacocoTestReport coveralls
